[application]

name = "t5-rs"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]

title = "t5.rs"
base_path = "t5.rs"

[web.watcher]

reload_html = true
watch_path = ["src", "assets"]

[web.resource]

style = ["./out/tailwind.css"]
script = []

[web.resource.dev]

script = []
